fix: allow optional nested folders
ileitch/swift-fnmatch pull request #1
Opened 2024-09-13 11:24 UTC by nekrich

Allow the `A/*/f` pattern to match the `A/f` file.

File list using `./**/*.swift` in this project root:
```shell
/bin/ls -1 ./**/*.swift
Package.swift
Sources/FilenameMatcher/FilenameMatcher.swift
Tests/FilenameMatcherTests/FilenameMatcherTests.swift
```

2024-09-14 11:35 UTC, ileitch requested changes
The description says
> Allow the A/*/f pattern to match the A/f file.

I assume this is a typo, and you meant `A/**/f`? I don't see any test for `A/*/f` specifically.

If the intent here is to match `ls` behavior, then the following test case should succeed:
```swift
assertMatch("a/c.txt", "a/*/c.txt", false)
```

2024-09-14 11:35 UTC, ileitch commented on Sources/FilenameMatcher/FilenameMatcher.swift
> +        let duplicatesRemoval: [String] = [
Looks like this doesn't need to be an array, as it's never mutated.

2024-12-15 11:22 UTC, SimplyDanny commented
Is there a chance you'd continue on this PR, @nekrich? It's the [only regression](https://github.com/realm/SwiftLint/pull/5157#issuecomment-2348581749) apart from significant performance improvements being reported in https://github.com/realm/SwiftLint/pull/5157. I'd really like to move this forward.

2024-12-15 15:04 UTC, ileitch commented
@SimplyDanny I'll take a look

2024-12-15 18:15 UTC, ileitch commented
@SimplyDanny I've released 2.0.0 with a new `.globstar` option that's enabled by default, so this should hopefully be resolved without any API changes needed in https://github.com/realm/SwiftLint/pull/5157.

BCR PR is wait for review: https://github.com/bazelbuild/bazel-central-registry/pull/3427

2024-12-15 18:15 UTC, closed without merging

2024-12-15 21:44 UTC, SimplyDanny commented
Awesome! Internal tests look promising. Thank you, @ileitch.